In [3]:
import numpy as np
arr= np.array([1,3,4,5,6])
print(arr)
print(arr.shape)

[1 3 4 5 6]
(5,)


In [5]:
arr1=np.array([1,3,4,5,6])
arr1.reshape(1,5)

array([[1, 3, 4, 5, 6]])

In [ ]:
#2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]


In [18]:
np.arange(0,10,2).reshape(1,5)#creating array in range 0 to 10 skipping every next element and further reshaped it

array([[0, 2, 4, 6, 8]])

In [22]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
#identity matrix
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
#attributes of nympy
arr4= np.array([[1,2,3,4,5],[3,5,6,7,8]])
print(arr4)
print(arr4.shape)
print(arr4.ndim)
print(arr4.size)
print(arr4.dtype)
print(arr4.itemsize)

[[1 2 3 4 5]
 [3 5 6 7 8]]
(2, 5)
2
10
int32
4


In [37]:
#numpy vectorized opreration
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,3,4,5,6])
print("Addition:", arr1+arr2)
#element wise substraction
print("substraciton",arr1-arr2)

Addition: [ 3  5  7  9 11]
substraciton [-1 -1 -1 -1 -1]


In [ ]:
#universal function
arr=np.array([3,4,5,6,6])
#square root
print(np.sqrt(arr))
#sine
print(np.sin(arr))
#exponential
print(np.exp(arr))
#natural log
print(np.log(arr))

[1.73205081 2.         2.23606798 2.44948974 2.44948974]
[ 0.14112001 -0.7568025  -0.95892427 -0.2794155  -0.2794155 ]
[ 20.08553692  54.59815003 148.4131591  403.42879349 403.42879349]
[1.09861229 1.38629436 1.60943791 1.79175947 1.79175947]


In [51]:
#slicing operation
arr=np.array([[2,3,4,5,6],[3,2,4,5,6],[2,4,6,8,9]])
print(arr)
print(arr[0])
print(arr[0][0])
print(arr[1:,2:])#first sliced row form index 1 and column from index 2 to end

[[2 3 4 5 6]
 [3 2 4 5 6]
 [2 4 6 8 9]]
[2 3 4 5 6]
2
[[4 5 6]
 [6 8 9]]


In [56]:
print(arr[0][0])
print(arr[0:2,2:])
print(arr[1:,1:4])

2
[[4 5 6]
 [4 5 6]]
[[2 4 5]
 [4 6 8]]


In [58]:
#modify array elements
arr[0,0]=100
print(arr)

[[100   3   4   5   6]
 [  3   2   4   5   6]
 [  2   4   6   8   9]]


In [62]:
#statistical concept->Normalization
arr=np.array([1,3,4,5,6])
mean= np.mean(arr)
std_dev=np.std(arr)
normalized_data=(arr-mean)/std_dev
print(normalized_data)
print(np.std(arr))
print(np.var(arr))
print(np.median(arr))

[-1.62746694 -0.46499055  0.11624764  0.69748583  1.27872403]
1.7204650534085253
2.96
4.0


In [ ]:
#logical operation
data=np.array([1,2,3,4,5,6,7,8])
print(data[(data>5) & (data<=8)])
print(data[(data>5) | (data<=8)])S



[6 7 8]
[1 2 3 4 5 6 7 8]
